const cards={
  freedom:{name:'Chase Freedom Unlimited®',short:'Freedom Unlimited',issuer:'Chase',fee:0,rates:{travel:5,dining:3,drugstore:3,other:1.5},features:['No annual fee','5% Chase Travel','3% dining','3% drugstores','Chase Offers','Purchase protection','Extended warranty','Trip cancellation/interruption']},
  prime:{name:'Prime Visa',short:'Prime Visa',issuer:'Amazon / Chase',fee:0,rates:{amazon:5,travel:5,gas:2,dining:2,transit:2,other:1},features:['No annual fee','5% Amazon / Whole Foods / Audible with Prime','5% Chase Travel with Prime','2% gas','2% restaurants','2% local transit / rideshare','Chase Offers','No foreign transaction fees','Purchase protection','Extended warranty']},
  amazonstore:{name:'Amazon Store Card',short:'Amazon Store Card',issuer:'Amazon / Synchrony',fee:0,rates:{},features:['No annual fee','Promotional financing on qualifying Amazon purchases','Amazon Pay acceptance','Zero fraud liability subject to terms']},
  smartly:{name:'U.S. Bank Smartly™ Visa Signature®',short:'U.S. Bank Smartly',issuer:'U.S. Bank',fee:0,rates:{other:2},features:['No annual fee','2% cash back on eligible purchases','Potential 2.5% / 3% / 4% with qualifying Smartly balances','Cash-back Deals','ExtendPay']},
  cashplus:{name:'U.S. Bank Cash+® Visa Signature®',short:'U.S. Bank Cash+',issuer:'U.S. Bank',fee:0,rates:{other:1},features:['No annual fee','Choose two 5% quarterly categories','Choose one 2% everyday category','1% other eligible purchases','5% eligible U.S. Bank Travel Center bookings','Cash-back Deals']},
  quicksilver:{name:'Capital One Quicksilver Rewards',short:'Quicksilver',issuer:'Capital One',fee:0,rates:{travel:5,entertainment:5,other:1.5},features:['No annual fee','1.5% cash back on eligible purchases','5% eligible Capital One Travel bookings','5% eligible Capital One Entertainment','Capital One Offers','CreditWise']},
  platinum:{name:'Capital One Platinum',short:'Capital One Platinum',issuer:'Capital One',fee:0,rates:{},features:['No annual fee','Credit-building features','CreditWise','Card lock']},
  discover:{name:'Discover it® Cash Back',short:'Discover it Cash Back',issuer:'Discover',fee:0,rates:{rotating5:5,other:1},features:['No annual fee','5% rotating categories after activation up to quarterly limit','1% other purchases','Cashback Match for eligible new cardmembers','$0 fraud liability','Card lock']},
  robinhoodgold:{name:'Robinhood Gold Card',short:'Robinhood Gold',issuer:'Robinhood',fee:0,rates:{travel:5,other:3},features:['3% back on eligible purchases','Up to 5X select travel through Robinhood Travel','Gold membership required','Cash redemption options']},
  oldnavy:{name:'Old Navy Encore Credit Card',short:'Old Navy Encore',issuer:'Old Navy / Barclays',fee:0,rates:{oldnavy:5,apparel:3,other:1},features:['25 points/$1 at Old Navy / Gap family','15 points/$1 at eligible apparel retailers','5 points/$1 elsewhere','500 points = $1 reward','30% first-purchase offer for eligible new cardmembers','Free shipping / birthday / extended-return benefits subject to terms']},
  bilt:{name:'Bilt Blue Rewards Card',short:'Bilt Blue',issuer:'Bilt',fee:0,rates:{other:1},features:['No annual fee','1X everyday Bilt Points','Housing rewards subject to current Bilt program','Optional Bilt Cash earning mode','No foreign transaction fees','Cellular protection subject to Guide to Benefits','Neighborhood Benefits']},
  dcu:{name:'DCU Visa Signature Cash Rewards',short:'DCU Cash Rewards',issuer:'DCU',fee:0,rates:{},features:['No annual fee','No balance transfer fee','No foreign transaction fee','No cash advance fee','Visa Signature benefits','Concierge','Travel protections','Roadside assistance','Emergency cash']}
};
const categoryLabels={amazon:'Amazon / Whole Foods / Audible',travel:'Travel',dining:'Dining',gas:'Gas / EV charging',drugstore:'Drugstore / Pharmacy',transit:'Transit / Rideshare',oldnavy:'Old Navy / Gap family',apparel:'Other apparel',entertainment:'Entertainment',electronics:'Electronics',grocery:'Grocery',other:'Everything else',rotating5:'Discover rotating 5%'};
const searchRules=[
  [['amazon','whole foods','audible'],'amazon'],[['flight','airline','hotel','rental car','travel','vacation'],'travel'],[['restaurant','dinner','lunch','food','doordash','grubhub','uber eats','dining'],'dining'],[['gas','fuel','ev charging'],'gas'],[['cvs','walgreens','rite aid','drugstore','pharmacy'],'drugstore'],[['uber','lyft','transit','bus','train','subway'],'transit'],[['old navy','gap','banana republic','athleta','gap factory'],'oldnavy'],[['nordstrom','macy','department store','clothing','apparel','nike','adidas'],'apparel'],[['movie','cinema','theater'],'entertainment'],[['electronics','best buy'],'electronics'],[['grocery','supermarket','groceries'],'grocery']]
];
const spendFields=[['amazon','Amazon / Whole Foods / Audible'],['travel','Travel'],['dining','Dining'],['gas','Gas'],['drugstore','Drugstore'],['transit','Transit'],['oldnavy','Old Navy / Gap family'],['apparel','Other apparel'],['other','Everything else']];
function money(n){return '$'+Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function getOffers(){try{return JSON.parse(localStorage.getItem('cro_offers')||'[]')}catch(e){return []}}
function activeOffer(o){return !o.expires||new Date(o.expires+'T23:59:59')>=new Date()}
function rateFor(id,cat){const c=cards[id];if(cat==='electronics'&&id==='cashplus')return 5;if(cat==='grocery'&&id==='cashplus')return 2;if(cat==='apparel'&&id==='oldnavy')return 3;if(cat==='oldnavy'&&id==='oldnavy')return 5;return c.rates[cat]??c.rates.other??null}
function renderCards(){const el=document.getElementById('cards');document.getElementById('cardCount').textContent=Object.keys(cards).length;el.innerHTML=Object.entries(cards).map(([id,c])=>{const rates=Object.entries(c.rates).slice(0,6);return `<article class="panel" onclick="openCardModal('${id}')"><div class="card-top"><div><h3>${esc(c.name)}</h3><div class="muted">${esc(c.issuer)}</div></div><span class="card-chip">View details →</span></div><div class="rates">${rates.length?rates.map(([k,v])=>`<div class="rate"><b>${v}%</b>${esc(categoryLabels[k]||k)}</div>`).join(''):'<div class="rate"><b>—</b>See details</div>'}</div><p class="muted">${c.features.length} tracked features · $${c.fee} annual fee</p></article>`}).join('')}
function renderBenefits(){document.getElementById('benefitCount').textContent=Object.values(cards).reduce((n,c)=>n+c.features.length,0);document.getElementById('benefits').innerHTML=Object.values(cards).flatMap(c=>c.features.map(f=>`<article class="benefit"><div class="type">${esc(c.short)}</div><h3>${esc(f)}</h3><div class="muted">Public benefit/rule currently tracked. Verify current issuer terms and account eligibility.</div></article>`)).join('')}
function offerHtml(o,expired){return `<article class="offer ${expired?'expired':''}"><span class="offer-status ${expired?'expired-tag':'active'}">${expired?'Expired':'Active'}</span><span class="tag">${esc(cards[o.card].name)}</span><h3>${esc(o.merchant)}</h3><div>${esc(o.offer)}</div>${o.expires?`<p class="muted">Expires ${esc(o.expires)}</p>`:''}</article>`}
function renderOffers(){const q=(document.getElementById('search')?.value||'').toLowerCase();const all=getOffers().filter(o=>cards[o.card]&&(String(o.merchant)+' '+cards[o.card].name+' '+String(o.offer)).toLowerCase().includes(q));const active=all.filter(activeOffer),expired=all.filter(o=>!activeOffer(o));document.getElementById('offerCount').textContent=getOffers().filter(activeOffer).length;let html=active.map(o=>offerHtml(o,false)).join('');if(expired.length)html+=`<div style="grid-column:1/-1"><h3>Expired</h3></div>`+expired.map(o=>offerHtml(o,true)).join('');document.getElementById('offers').innerHTML=html||'<div class="empty">No personal offers yet. Add an offer you see in your issuer account.</div>'}
function initOfferCards(){document.getElementById('offerCard').innerHTML=Object.entries(cards).map(([id,c])=>`<option value="${id}">${esc(c.name)}</option>`).join('')}
function saveOffer(){const merchant=document.getElementById('merchant').value.trim(),offer=document.getElementById('offerText').value.trim(),card=document.getElementById('offerCard').value,expires=document.getElementById('expires').value;if(!merchant||!offer){alert('Please enter a merchant and offer.');return}const list=getOffers();list.unshift({merchant,offer,card,expires});localStorage.setItem('cro_offers',JSON.stringify(list));document.getElementById('merchant').value='';document.getElementById('offerText').value='';document.getElementById('expires').value='';closeOfferModal();renderOffers()}
function openOfferModal(){document.getElementById('modal').classList.remove('hidden')}function closeOfferModal(){document.getElementById('modal').classList.add('hidden')}function openCompareModal(){document.getElementById('fullComparison').innerHTML=document.getElementById('comparison').innerHTML;document.getElementById('compareModal').classList.remove('hidden')}function closeCompareModal(){document.getElementById('compareModal').classList.add('hidden')}function closeCardModal(){document.getElementById('cardModal').classList.add('hidden')}
function openCardModal(id){const c=cards[id];document.getElementById('cardDetails').innerHTML=`<div class="detail-hero"><div><div class="type">${esc(c.issuer)}</div><h2>${esc(c.name)}</h2><div class="muted">$${c.fee} annual fee</div></div><button class="secondary" onclick="closeCardModal()">Close</button></div><div class="detail-section"><h3>Configured reward rates</h3><div class="detail-grid">${Object.entries(c.rates).length?Object.entries(c.rates).map(([k,v])=>`<div class="detail-item"><b>${v}%</b><span class="muted">${esc(categoryLabels[k]||k)}</span></div>`).join(''):'<div class="detail-item"><b>Not configured</b><span class="muted">No standard cash-back rate is configured.</span></div>'}</div></div><div class="detail-section"><h3>Features & benefits</h3><div class="detail-grid">${c.features.map(f=>`<div class="detail-item"><b>${esc(f)}</b><span class="muted">Verify current issuer terms, exclusions and eligibility.</span></div>`).join('')}</div></div><div class="source-note">Rhino Rewards public-data snapshot. Account-specific offers and terms are not accessed. Your issuer account and current card agreement control.</div>`;document.getElementById('cardModal').classList.remove('hidden')}
function renderComparison(){const ids=Object.keys(cards);let html='<table class="compare-table"><thead><tr><th>Category / feature</th>'+ids.map(id=>`<th>${esc(cards[id].short)}</th>`).join('')+'</tr></thead><tbody>';['amazon','travel','dining','gas','drugstore','transit','oldnavy','apparel','other'].forEach(k=>{html+=`<tr><td>${esc(categoryLabels[k])}</td>`+ids.map(id=>{const r=rateFor(id,k);return `<td>${r==null?'—':'<strong>'+r+'%</strong>'}</td>`}).join('')+`</tr>`});html+=`<tr><td>Annual fee</td>`+ids.map(id=>`<td>$${cards[id].fee}</td>`).join('')+`</tr><tr><td>Tracked features</td>`+ids.map(id=>`<td>${cards[id].features.length}</td>`).join('')+`</tr></tbody></table>`;document.getElementById('comparison').innerHTML=html}
function calculate(){const amount=Number(document.getElementById('amount').value)||0,cat=document.getElementById('category').value;const vals=Object.entries(cards).map(([id,c])=>({name:c.name,pct:rateFor(id,cat),value:amount*(rateFor(id,cat)||0)/100})).sort((a,b)=>(b.pct??-1)-(a.pct??-1));document.getElementById('result').innerHTML=vals.map(x=>`<div class="result-row"><strong>${esc(x.name)}</strong> — ${x.pct==null?'No cash-back rate configured':x.pct+'% = '+money(x.value)}</div>`).join('')}
function detectCategory(q){const t=q.toLowerCase();for(const [terms,cat] of searchRules)if(terms.some(x=>t.includes(x)))return {cat,label:categoryLabels[cat]};return {cat:'other',label:categoryLabels.other}}
function matchingOffer(id,q){const t=q.toLowerCase();return getOffers().find(o=>o.card===id&&activeOffer(o)&&t.includes(String(o.merchant).toLowerCase()))}
function searchPurchase(){const q=(document.getElementById('purchaseSearch')?.value||'').trim(),amount=Number(document.getElementById('purchaseAmount')?.value)||0;if(!q){document.getElementById('purchaseResult').innerHTML='<div class="empty">Search for a purchase above to see the card comparison.</div>';return}const rule=detectCategory(q);const results=Object.entries(cards).map(([id,c])=>{const pct=rateFor(id,rule.cat);return {id,name:c.name,pct,value:pct==null?null:amount*pct/100,offer:matchingOffer(id,q)}}).sort((a,b)=>(b.pct??-1)-(a.pct??-1));const top=results.find(x=>x.pct!=null);let html=`<div class="purchase-summary"><div class="type">MATCHED CATEGORY</div><h3>${esc(rule.label)}</h3><p class="muted">${esc(q)} · ${money(amount)}</p></div>`;if(top)html+=`<div class="purchase-top"><span class="offer-status active">Highest configured cash-back rate</span><h2>${esc(top.name)}</h2><p><strong>${top.pct}%</strong> estimated reward = <strong>${money(top.value)}</strong></p>${top.offer?`<p class="muted">Personal offer: ${esc(top.offer.offer)}</p>`:''}</div>`;html+=`<div class="purchase-list">${results.map(x=>`<div class="result-row"><strong>${esc(x.name)}</strong> <span>${x.pct==null?'No standard cash-back rate':x.pct+'% · '+money(x.value)}</span>${x.offer?`<div class="muted">Personal offer: ${esc(x.offer.offer)}</div>`:''}</div>`).join('')}</div><p class="muted">Uses configured public rates. Personalized issuer offers and rotating categories must be verified in the issuer account.</p>`;document.getElementById('purchaseResult').innerHTML=html}
function quickPurchase(text,amount){document.getElementById('purchaseSearch').value=text;document.getElementById('purchaseAmount').value=amount;searchPurchase()}
function renderSpendInputs(){document.getElementById('spendInputs').innerHTML=spendFields.map(([k,t])=>`<label>${esc(t)}<input class="spend-input" data-cat="${k}" type="number" min="0" value="0"></label>`).join('')}
function evaluateSpending(){const spend=Object.fromEntries([...document.querySelectorAll('.spend-input')].map(x=>[x.dataset.cat,Number(x.value)||0]));const results=Object.entries(cards).map(([id,c])=>{let annual=0;Object.entries(spend).forEach(([cat,m])=>{const pct=rateFor(id,cat);if(pct!=null)annual+=m*12*pct/100});return {name:c.name,annual}});const max=Math.max(...results.map(x=>x.annual),0);document.getElementById('profileValue').textContent=money(max);document.getElementById('evaluation').innerHTML='<p class="muted">Estimated annual cash rewards from configured rates only.</p><div class="eval-grid">'+results.map(x=>`<div class="eval-card"><b>${esc(x.name)}</b><div class="eval-value">${money(x.annual)}</div><div class="bar"><i style="width:${max?Math.max(3,x.annual/max*100):0}%"></i></div></div>`).join('')+'</div>'}
function resetSpending(){document.querySelectorAll('.spend-input').forEach(x=>x.value=0);document.getElementById('profileValue').textContent='$0';document.getElementById('evaluation').innerHTML=''}
function init(){renderCards();renderBenefits();initOfferCards();renderOffers();renderComparison();renderSpendInputs();calculate()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
