const cards={
  freedom:{name:'Chase Freedom Unlimited®',short:'Freedom Unlimited',subtitle:'Chase',fee:0,network:'Visa',rates:{travel:5,dining:3,drugstore:3,other:1.5},conditions:['5% Chase Travel.','3% dining.','3% drugstores.','1.5% other eligible purchases.'],features:[['No annual fee','No annual fee.'],['Chase Offers','Eligible cardmembers may receive targeted offers in the Chase app or chase.com.'],['DashPass','Eligible DashPass promotion; terms and activation requirements apply.'],['Lyft','Eligible Lyft promotion; current terms apply.'],['Purchase Protection','Eligible purchases can be covered for 120 days against damage or theft, subject to limits.'],['Extended Warranty','Eligible warranties of 3 years or less may receive an additional year, subject to terms.'],['Trip Cancellation / Interruption','Coverage may apply to eligible prepaid, non-refundable travel, subject to terms.']],source:'Chase Freedom Unlimited public information checked Sept. 16, 2026.'},
  prime:{name:'Prime Visa',short:'Prime Visa',subtitle:'Amazon / Chase',fee:0,network:'Visa',rates:{amazon:5,travel:5,gas:2,dining:2,transit:2,other:1},conditions:['5% Amazon, Whole Foods, Audible and Chase Travel with eligible Prime membership.','2% gas, restaurants and local transit/commuting including rideshare.','1% other eligible purchases.'],features:[['No annual fee','No annual credit card fee.'],['Amazon rewards','5% back on eligible Amazon/Whole Foods/Audible purchases with Prime.'],['Chase Offers','Eligible customers may receive targeted offers.'],['No foreign transaction fees','No foreign transaction fees.'],['Purchase Protection','Eligible new purchases covered for 120 days, subject to limits.'],['Extended Warranty','Eligible warranties may receive an additional year, subject to terms.'],['Baggage / travel protections','Various travel protections may apply; see current Guide to Benefits.']],source:'Chase Prime Visa public information checked Sept. 16, 2026.'},
  amazonstore:{name:'Amazon Store Card',short:'Amazon Store Card',subtitle:'Amazon / Synchrony',fee:0,network:'Store Card',rates:{},conditions:['Designed primarily for Amazon purchases.','Promotional financing is available on qualifying purchases; terms depend on the offer shown at checkout.'],features:[['No annual fee','No annual fee.'],['Promotional financing','Qualifying Amazon purchases may receive promotional financing such as 6, 12 or 24 months, depending on the offer.'],['Amazon Pay','Can be used at participating Amazon Pay merchants.'],['Zero fraud liability','Amazon states unauthorized-use protection applies subject to terms.']],source:'Amazon/Amazon Pay public information checked Sept. 16, 2026.'},
  smartly:{name:'U.S. Bank Smartly™ Visa Signature®',short:'U.S. Bank Smartly',subtitle:'U.S. Bank',fee:0,network:'Visa',rates:{other:2},conditions:['Unlimited 2% cash back on every purchase.','Potential 2.5%, 3% or 4% on the first $10,000 of eligible net purchases each billing cycle when qualifying U.S. Bank Smartly deposit balances are met.'],features:[['No annual fee','$0 annual fee.'],['Smartly Earning Bonus','Qualifying balances can increase the effective cash-back rate to 2.5%, 3% or 4% on the first $10,000 of eligible net purchases per billing cycle.'],['Cash-back deals','U.S. Bank offers personalized Cash-back Deals based on spending.'],['ExtendPay','Eligible purchases may qualify for U.S. Bank ExtendPay plans; terms apply.']],source:'U.S. Bank public Smartly Visa Signature page checked Sept. 16, 2026.'},
  cashplus:{name:'U.S. Bank Cash+® Visa Signature®',short:'U.S. Bank Cash+',subtitle:'U.S. Bank',fee:0,network:'Visa',rates:{other:1},conditions:['Choose two 5% categories each quarter, up to $2,000 combined net purchases per quarter.','Choose one 2% everyday category.','Other eligible purchases earn 1%.','Prepaid air, hotel and car reservations through the U.S. Bank Travel Center can earn 5%.'],features:[['Quarterly 5% categories','Two categories must be selected each quarter.'],['2% category','Choose one everyday category such as gas/EV charging, restaurants or grocery, subject to current category rules.'],['Travel Center','Eligible prepaid air, hotel and car reservations can earn 5%.'],['Cash-back deals','U.S. Bank also provides personalized Cash-back Deals.']],source:'U.S. Bank Cash+ public information checked Sept. 16, 2026.'},
  quicksilver:{name:'Capital One Quicksilver Rewards',short:'Quicksilver',subtitle:'Capital One',fee:0,network:'Visa/Mastercard',rates:{travel:5,other:1.5},conditions:['1.5% cash back on every purchase.','5% cash back on eligible hotels, vacation rentals, rental cars and activities booked through Capital One Travel.','5% cash back on eligible Capital One Entertainment purchases.'],features:[['No annual fee','$0 annual fee.'],['Welcome bonus','Current public offer may include a $200 cash bonus after qualifying spend; offer terms can change and existing cardholders may not qualify.'],['Capital One Offers','Eligible customers can access targeted shopping offers through Capital One.'],['Capital One Entertainment','Eligible purchases can earn 5%.'],['Capital One Travel','Eligible bookings can earn 5%.'],['CreditWise','Free credit monitoring tools are available.']],source:'Capital One public Quicksilver information checked Sept. 16, 2026.'},
  platinum:{name:'Capital One Platinum',short:'Capital One Platinum',subtitle:'Capital One',fee:0,network:'Visa/Mastercard',rates:{},conditions:['No rewards program is advertised on the current public Platinum card page.'],features:[['No annual fee','$0 annual fee.'],['Credit building','Designed for building credit with responsible use.'],['CreditWise','Capital One provides free credit monitoring tools.'],['Card lock','Capital One account controls can help lock a card if misplaced.']],source:'Capital One public Platinum information checked Sept. 16, 2026.'},
  discover:{name:'Discover it® Cash Back',short:'Discover it Cash Back',subtitle:'Discover',fee:0,network:'Discover',rates:{rotating5:5,other:1},conditions:['5% cash back at different places each quarter, up to the quarterly maximum, when activated.','1% on other purchases.','The current quarterly 5% merchants/categories should be verified in the Discover account because they rotate.'],features:[['Unlimited Cashback Match','New cardmembers may receive an unlimited dollar-for-dollar match of cash back earned during the first year.'],['Quarterly activation','5% categories require activation and have a quarterly maximum.'],['No annual fee','$0 annual fee.'],['$0 fraud liability','Discover states cardmembers are not responsible for unauthorized purchases, subject to terms.'],['Card Lock','Card can be locked in the Discover app if misplaced.']],source:'Discover public it Cash Back information checked Sept. 16, 2026.'},
  robinhoodgold:{name:'Robinhood Gold Card',short:'Robinhood Gold',subtitle:'Robinhood',fee:0,network:'Visa',rates:{travel:5,other:3},conditions:['3% back on eligible purchases.','Up to 5X points on select travel booked through the Robinhood travel portal.','Gold membership is required; current Gold subscription pricing and terms apply.'],features:[['3% everyday rewards','Default Gold Card earning is 3X points on eligible purchases.'],['5X travel','Eligible travel booked through the Robinhood Travel Portal can earn up to 5X.'],['Gold membership','Card is associated with a Robinhood Gold subscription.'],['Cash redemption','Points can be redeemed through available options including cash/brokerage cash; redemption values vary by method.']],source:'Robinhood public Gold Card information checked Sept. 16, 2026.'},
  oldnavy:{name:'Old Navy Encore Credit Card',short:'Old Navy Encore',subtitle:'Old Navy / Barclays',fee:0,network:'Mastercard',rates:{oldnavy:5,apparel:3,other:1},points:{oldnavy:25,apparel:15,other:5},conditions:['All-Access Encore cardmembers earn 25 points/$1 at the family of brands.','3X points, or 15 points/$1, at other eligible retail apparel brands.','1X points, or 5 points/$1, everywhere else Mastercard is accepted.','500 points = $1 reward according to the current Encore FAQ.'],features:[['30% first-purchase discount','Current public offer says new Encore cardmembers can receive 30% off a first purchase, subject to approval and terms.'],['Free shipping','Eligible cardmembers can receive free shipping when applicable thresholds are met.'],['Encore Market','Redeem points for eligible rewards and experiences.'],['Birthday bonus','Encore cardmembers can receive a birthday bonus.'],['Extended returns','All-Access cardmembers have extended return benefits subject to terms.']],source:'Old Navy Encore public information checked Sept. 16, 2026.'},
  bilt:{name:'Bilt Blue Rewards Card',short:'Bilt Blue',subtitle:'Bilt',fee:0,network:'Cardless / Visa',rates:{other:1},conditions:['1X Bilt Points on everyday purchases.','Up to 1.25X points on eligible rent and mortgage payments depending on selected Bilt rewards option.','Optional Flexible Bilt Cash mode can add 4% Bilt Cash on everyday spend.'],features:[['$0 annual fee','No annual fee.'],['Housing rewards','Rent and mortgage payments can earn rewards with no transaction fee through Bilt, subject to program rules.'],['4% Bilt Cash option','Choose Flexible Bilt Cash to earn 4% Bilt Cash on everyday purchases in addition to card points.'],['No foreign transaction fees','No foreign transaction fees.'],['Cellular wireless protection','Bilt Blue includes cellular wireless telephone protection subject to the Guide to Benefits.'],['Neighborhood Benefits','Eligible partner merchants can provide additional rewards.']],source:'Bilt Card 2.0 public information checked Sept. 16, 2026.'},
  dcu:{name:'DCU Visa Signature Cash Rewards',short:'DCU Cash Rewards',subtitle:'DCU / First Tech',fee:0,network:'Visa',rates:{},conditions:['Current public DCU page confirms the Visa Signature Cash Rewards card but does not expose a current reward rate in the public page content reviewed.'],features:[['No annual fee','DCU lists no annual fee.'],['No balance transfer fee','DCU lists no balance transfer fee.'],['No foreign transaction fee','DCU lists no foreign transaction fee.'],['No cash advance fee','DCU lists no cash advance fee.'],['Visa Signature benefits','Includes Visa Signature Luxury Hotel Collection and other Visa Signature services.'],['24/7 Visa Signature Concierge','Concierge can assist with travel, events and reservations.'],['Travel protections','Travel coverage/emergency assistance may apply.'],['Roadside assistance','24/7 roadside assistance program access.'],['Emergency cash','Emergency cash disbursement access.']],source:'DCU public Visa Signature Cash Rewards information checked Sept. 16, 2026.'}
};

const spendFields=[['amazon','Amazon / Whole Foods / Audible'],['travel','Travel'],['dining','Dining'],['gas','Gas'],['drugstore','Drugstore'],['transit','Transit'],['oldnavy','Old Navy / Gap family'],['apparel','Other apparel'],['other','Everything else']];
const searchRules=[
  {terms:['amazon','whole foods','audible'],cat:'amazon',label:'Amazon / Whole Foods / Audible'},
  {terms:['flight','airline','hotel','rental car','travel','vacation'],cat:'travel',label:'Travel'},
  {terms:['restaurant','dinner','lunch','food','doordash','grubhub','uber eats','dining'],cat:'dining',label:'Dining'},
  {terms:['gas','fuel','ev charging'],cat:'gas',label:'Gas / EV charging'},
  {terms:['cvs','walgreens','rite aid','drugstore','pharmacy'],cat:'drugstore',label:'Drugstore / Pharmacy'},
  {terms:['uber','lyft','transit','bus','train','subway'],cat:'transit',label:'Transit / Rideshare'},
  {terms:['old navy','gap','banana republic','athleta','gap factory'],cat:'oldnavy',label:'Old Navy / Gap family'},
  {terms:['nordstrom','macy','department store','clothing','apparel','nike','adidas'],cat:'apparel',label:'Apparel'},
  {terms:['movie','cinema','theater'],cat:'entertainment',label:'Entertainment'},
  {terms:['electronics','best buy'],cat:'electronics',label:'Electronics'},
  {terms:['grocery','supermarket','groceries'],cat:'grocery',label:'Grocery'}
];
function money(n){return '$'+Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}
function label(k){return ({amazon:'Amazon / Whole Foods / Audible',travel:'Travel',dining:'Dining',drugstore:'Drugstore / Pharmacy',gas:'Gas / EV charging',transit:'Transit / Rideshare',oldnavy:'Old Navy / Gap family',apparel:'Other apparel',other:'Everything else',rotating5:'Discover rotating 5% category',entertainment:'Entertainment',electronics:'Electronics',grocery:'Grocery'})[k]||k}
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function getOffers(){try{return JSON.parse(localStorage.getItem('cro_offers')||'[]')}catch{return []}}
function offerActive(o){if(!o.expires)return true;return new Date(o.expires+'T23:59:59')>=new Date()}
function initOfferCards(){const s=document.getElementById('offerCard');if(!s)return;s.innerHTML=Object.entries(cards).map(([id,c])=>`<option value="${id}">${c.name}</option>`).join('')}
function renderCards(){document.getElementById('cardCount').textContent=Object.keys(cards).length;document.getElementById('cards').innerHTML=Object.entries(cards).map(([id,c])=>{const rateItems=Object.entries(c.rates);return `<article class="panel" onclick="openCardModal('${id}')"><div class="card-top"><div><h3>${c.name}</h3><div class="muted">${c.subtitle} · ${c.network}</div></div><span class="card-chip">View details →</span></div><div class="rates">${rateItems.length?rateItems.slice(0,6).map(([k,v])=>`<div class="rate"><b>${v}%</b>${label(k)}</div>`).join(''):`<div class="rate"><b>—</b>See details</div>`}</div><p class="muted">${c.features.length} tracked features · $${c.fee} annual fee</p></article>`}).join('')}
function renderBenefits(){document.getElementById('benefitCount').textContent=Object.values(cards).reduce((n,c)=>n+c.features.length,0);document.getElementById('benefits').innerHTML=Object.entries(cards).flatMap(([id,c])=>c.features.map(([t,d])=>`<article class="benefit"><div class="type">${c.short}</div><h3>${t}</h3><div class="muted">${d}</div></article>`)).join('')}
function renderOffers(){const q=(document.getElementById('search')?.value||'').toLowerCase();const all=getOffers().filter(o=>cards[o.card]&&(o.merchant+' '+cards[o.card].name+' '+o.offer).toLowerCase().includes(q));const active=all.filter(offerActive),expired=all.filter(o=>!offerActive(o));document.getElementById('offerCount').textContent=getOffers().filter(offerActive).length;let html=active.map(o=>offerHtml(o,false)).join('');if(expired.length)html+=`<div style="grid-column:1/-1;margin-top:10px"><h3>Expired</h3></div>`+expired.map(o=>offerHtml(o,true)).join('');document.getElementById('offers').innerHTML=html||`<div class="empty">No personal offers yet. Add an offer you see in your card account.</div>`}
function offerHtml(o,isExpired){return `<article class="offer ${isExpired?'expired':''}"><span class="offer-status ${isExpired?'expired-tag':'active'}">${isExpired?'Expired':'Active'}</span><span class="tag">${escapeHtml(cards[o.card].name)}</span><h3>${escapeHtml(o.merchant)}</h3><div>${escapeHtml(o.offer)}</div>${o.expires?`<p class="muted">Expires ${escapeHtml(o.expires)}</p>`:''}</article>`}
function openOfferModal(){document.getElementById('modal').classList.remove('hidden')};function closeOfferModal(){document.getElementById('modal').classList.add('hidden')}
function saveOffer(){const merchant=document.getElementById('merchant').value.trim(),offer=document.getElementById('offerText').value.trim(),card=document.getElementById('offerCard').value,expires=document.getElementById('expires').value;if(!merchant||!offer)return alert('Please enter a merchant and offer.');const list=getOffers();list.unshift({merchant,offer,card,expires});localStorage.setItem('cro_offers',JSON.stringify(list));document.getElementById('merchant').value='';document.getElementById('offerText').value='';document.getElementById('expires').value='';closeOfferModal();renderOffers();}
function findMatchingOffer(card,query){const q=query.toLowerCase();return getOffers().find(o=>o.card===card&&offerActive(o)&&(q.includes(o.merchant.toLowerCase())||o.merchant.toLowerCase().split(/\s+/).some(w=>w.length>3&&q.includes(w))))}
function rateFor(card,cat){const c=cards[card];if(cat==='entertainment'&&card==='quicksilver')return 5;if(cat==='electronics'&&card==='cashplus')return 5;if(cat==='grocery'&&card==='cashplus')return 2;if(cat==='apparel'&&card==='oldnavy')return 3;if(cat==='oldnavy'&&card==='oldnavy')return 5;return c.rates[cat]??c.rates.other??null}
function calculate(){const amount=Number(document.getElementById('amount').value)||0,cat=document.getElementById('category').value;const vals=Object.entries(cards).map(([id,c])=>({id,name:c.name,pct:rateFor(id,cat),value:amount*(rateFor(id,cat)||0)/100}));document.getElementById('result').innerHTML=vals.sort((a,b)=>(b.pct||0)-(a.pct||0)).map(x=>`<div class="result-row"><strong>${x.name}</strong> — ${x.pct==null?'No cash-back rate configured':x.pct+'% = '+money(x.value)}</div>`).join('')}
function detectCategory(q){const text=q.toLowerCase();for(const r of searchRules)if(r.terms.some(t=>text.includes(t)))return r;return {cat:'other',label:'Everything else'} }
function searchPurchase(){const q=(document.getElementById('purchaseSearch')?.value||'').trim();const amount=Number(document.getElementById('purchaseAmount')?.value)||0;if(!q){document.getElementById('purchaseResult').innerHTML='<div class="empty">Search for a purchase above to see the card comparison.</div>';return}const rule=detectCategory(q);const results=Object.entries(cards).map(([id,c])=>{const pct=rateFor(id,rule.cat);const offer=findMatchingOffer(id,q);const special=(rule.cat==='travel'&&id==='robinhoodgold')?'Robinhood Travel Portal can earn up to 5X':(rule.cat==='travel'&&id==='quicksilver')?'Capital One Travel can earn 5%':(rule.cat==='oldnavy'&&id==='oldnavy')?'25 points/$1 at the Old Navy/Gap family':(rule.cat==='apparel'&&id==='oldnavy')?'15 points/$1 at eligible retail apparel brands':(rule.cat==='amazon'&&id==='amazonstore')?'Promotional financing may apply; this card does not earn a standard rewards rate':null;return {id,name:c.name,pct,value:pct==null?null:amount*pct/100,offer,special}}).sort((a,b)=>(b.pct??-1)-(a.pct??-1));const ranked=results.filter(x=>x.pct!=null);const top=ranked[0];let html=`<div class="purchase-summary"><div class="type">MATCHED CATEGORY</div><h3>${escapeHtml(rule.label)}</h3><p class="muted">${escapeHtml(q)} · ${money(amount)}</p></div>`;if(top)html+=`<div class="purchase-top"><div><span class="offer-status active">Highest configured cash-back rate</span><h2>${escapeHtml(top.name)}</h2><p><strong>${top.pct}%</strong> estimated reward = <strong>${money(top.value)}</strong></p>${top.offer?`<p class="muted">Personal offer: ${escapeHtml(top.offer.offer)}</p>`:''}</div></div>`;html+=`<div class="purchase-list">${results.map(x=>`<div class="result-row"><strong>${escapeHtml(x.name)}</strong> <span>${x.pct==null?'No standard cash-back rate':x.pct+'% · '+money(x.value)}</span>${x.offer?`<div class="muted">Personal offer: ${escapeHtml(x.offer.offer)}</div>`:''}${x.special?`<div class="muted">${escapeHtml(x.special)}</div>`:''}</div>`).join('')}</div><p class="muted">This comparison uses the public rates currently configured in Rhino Rewards. Personalized issuer offers, rotating categories and account-specific eligibility can change.</p>`;document.getElementById('purchaseResult').innerHTML=html}
function quickPurchase(text,amount){document.getElementById('purchaseSearch').value=text;document.getElementById('purchaseAmount').value=amount;searchPurchase()}
function renderComparison(){const ids=Object.keys(cards);let html='<table class="compare-table"><thead><tr><th>Category / feature</th>'+ids.map(id=>`<th>${escapeHtml(cards[id].short)}</th>`).join('')+'</tr></thead><tbody>';['amazon','travel','dining','gas','drugstore','transit','oldnavy','apparel','other'].forEach(k=>html+=`<tr><td>${label(k)}</td>`+ids.map(id=>{const r=rateFor(id,k);return `<td>${r==null?'—':'<strong>'+r+'%</strong>'}</td>`}).join('')+'</tr>');html+=`<tr><td>Annual fee</td>`+ids.map(id=>`<td>$${cards[id].fee}</td>`).join('')+'</tr><tr><td>Tracked features</td>`+ids.map(id=>`<td>${cards[id].features.length}</td>`).join('')+'</tr></tbody></table>`;document.getElementById('comparison').innerHTML=html}
function openCompareModal(){document.getElementById('fullComparison').innerHTML=document.getElementById('comparison').innerHTML;document.getElementById('compareModal').classList.remove('hidden')};function closeCompareModal(){document.getElementById('compareModal').classList.add('hidden')}
function openCardModal(id){const c=cards[id];document.getElementById('cardDetails').innerHTML=`<div class="detail-hero"><div><div class="type">${escapeHtml(c.subtitle)}</div><h2>${escapeHtml(c.name)}</h2><div class="muted">${escapeHtml(c.network)} · $${c.fee} annual fee</div></div><button class="secondary" onclick="closeCardModal()">Close</button></div><div class="detail-section"><h3>Reward rates</h3><div class="detail-grid">${Object.keys(c.rates).length?Object.entries(c.rates).map(([k,v])=>`<div class="detail-item"><b>${v}%</b><span class="muted">${label(k)}</span></div>`).join(''):`<div class="detail-item"><b>Not configured</b><span class="muted">No standard cash-back rate was verified for this card.</span></div>`}</div></div><div class="detail-section"><h3>Reward conditions</h3><ul class="detail-list">${c.conditions.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul></div><div class="detail-section"><h3>Features & benefits</h3><div class="detail-grid">${c.features.map(([t,d])=>`<div class="detail-item"><b>${escapeHtml(t)}</b><span class="muted">${escapeHtml(d)}</span></div>`).join('')}</div></div><div class="source-note">${escapeHtml(c.source)} Benefits and offers have eligibility requirements, limitations and exclusions. Your account terms control.</div>`;document.getElementById('cardModal').classList.remove('hidden')}
function closeCardModal(){document.getElementById('cardModal').classList.add('hidden')}
function renderSpendInputs(){document.getElementById('spendInputs').innerHTML=spendFields.map(([k,t])=>`<label>${t}<input class="spend-input" data-cat="${k}" type="number" min="0" value="0"></label>`).join('')}
function evaluateSpending(){const spend=Object.fromEntries([...document.querySelectorAll('.spend-input')].map(x=>[x.dataset.cat,Number(x.value)||0]));const results=Object.entries(cards).map(([id,c])=>{let annual=0;const breakdown=[];Object.entries(spend).forEach(([cat,monthly])=>{const yearly=monthly*12,pct=rateFor(id,cat);if(pct!=null&&yearly){const reward=yearly*pct/100;annual+=reward;breakdown.push([cat,reward])}});return {id,name:c.name,annual,breakdown}});const max=Math.max(...results.map(x=>x.annual),0);document.getElementById('profileValue').textContent=money(max);document.getElementById('evaluation').innerHTML=`<p class="muted">Estimated annual cash rewards from configured rates. Points currencies, personal offers, rotating categories and account-specific bonuses are not converted unless the dashboard has enough information to do so safely.</p><div class="eval-grid">${results.map(x=>`<div class="eval-card"><b>${escapeHtml(x.name)}</b><div class="eval-value">${money(x.annual)}</div><div class="bar"><i style="width:${max?Math.max(3,x.annual/max*100):0}%"></i></div><p class="muted">${x.breakdown.map(([k,v])=>`${label(k)}: ${money(v)}`).join(' · ')||'Enter monthly spending above.'}</p></div>`).join('')}</div>`}
function resetSpending(){document.querySelectorAll('.spend-input').forEach(x=>x.value=0);document.getElementById('profileValue').textContent='$0';document.getElementById('evaluation').innerHTML=''}
renderCards();renderBenefits();initOfferCards();renderOffers();renderComparison();renderSpendInputs();calculate();