const cards={freedom:{name:'Chase Freedom Unlimited®',subtitle:'Chase',rates:{travel:5,dining:3,drugstore:3,other:1.5}},prime:{name:'Prime Visa',subtitle:'Amazon / Chase',rates:{amazon:5,travel:5,gas:2,dining:2,transit:2,other:1}}};
const benefits=[['freedom','Purchase Protection','Covers eligible purchases for 120 days, subject to current terms and limits.'],['freedom','Trip Cancellation / Interruption','Coverage may apply to eligible prepaid travel expenses under current card terms.'],['freedom','Extended Warranty','Eligible purchases may receive additional warranty coverage under current terms.'],['freedom','Auto Rental Coverage','Rental-car coverage may apply when eligibility requirements are met.'],['prime','No Foreign Transaction Fee','Prime Visa currently has no foreign transaction fee.'],['prime','Purchase Protection','Eligible purchases may have purchase protection under current terms.'],['prime','Extended Warranty','Eligible purchases may receive extended warranty benefits under current terms.'],['prime','Lost Luggage Reimbursement','Eligible travel purchases may qualify under current terms.']];
function money(n){return '$'+Number(n).toFixed(2)}
function renderCards(){document.getElementById('cards').innerHTML=Object.entries(cards).map(([id,c])=>`<div class="panel"><h3>${c.name}</h3><div class="muted">${c.subtitle}</div><div class="rates">${Object.entries(c.rates).map(([k,v])=>`<div class="rate"><b>${v}%</b>${label(k)}</div>`).join('')}</div></div>`).join('')}
function label(k){return ({amazon:'Amazon / Whole Foods',travel:'Chase Travel',dining:'Dining',drugstore:'Drugstore',gas:'Gas',transit:'Transit',other:'Everything else'})[k]||k}
function renderBenefits(){document.getElementById('benefits').innerHTML=benefits.map(([id,t,d])=>`<div class="benefit"><div class="muted">${cards[id].name}</div><h3>${t}</h3><div class="muted">${d}</div></div>`).join('')}
function getOffers(){try{return JSON.parse(localStorage.getItem('cro_offers')||'[]')}catch{return []}}
function renderOffers(){const q=(document.getElementById('search').value||'').toLowerCase();const offers=getOffers().filter(o=>(o.merchant+' '+cards[o.card].name+' '+o.offer).toLowerCase().includes(q));document.getElementById('offerCount').textContent=offers.length;document.getElementById('offers').innerHTML=offers.length?offers.map(o=>`<div class="offer"><span class="tag">${cards[o.card].name}</span><h3>${escapeHtml(o.merchant)}</h3><div>${escapeHtml(o.offer)}</div>${o.expires?`<p class="muted">Expires ${o.expires}</p>`:''}</div>`).join(''):`<div class="empty">No personal offers yet. Add an offer you see in your card account.</div>`}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function openOfferModal(){document.getElementById('modal').classList.remove('hidden')};function closeOfferModal(){document.getElementById('modal').classList.add('hidden')}
function saveOffer(){const merchant=document.getElementById('merchant').value.trim(),offer=document.getElementById('offerText').value.trim(),card=document.getElementById('offerCard').value,expires=document.getElementById('expires').value;if(!merchant||!offer)return alert('Please enter a merchant and offer.');const list=getOffers();list.unshift({merchant,offer,card,expires});localStorage.setItem('cro_offers',JSON.stringify(list));document.getElementById('merchant').value='';document.getElementById('offerText').value='';document.getElementById('expires').value='';closeOfferModal();renderOffers()}
function calculate(){const amount=Number(document.getElementById('amount').value)||0,cat=document.getElementById('category').value;const vals=Object.entries(cards).map(([id,c])=>({id,name:c.name,pct:c.rates[cat]??c.rates.other,value:amount*(c.rates[cat]??c.rates.other)/100})).sort((a,b)=>b.value-a.value);document.getElementById('result').innerHTML=vals.map((x,i)=>`<div style="margin:7px 0"><strong>${i===0?'Highest configured reward: ':''}${x.name}</strong> — ${x.pct}% = ${money(x.value)}</div>`).join('')}
renderCards();renderBenefits();renderOffers();calculate();
